default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2344 # Sua senha atual para o usuário postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: horsesinpocket_development

test:
  <<: *default
  database: horsesinpocket_test


production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  sslmode: <%= ENV['DATABASE_SSLMODE'] %>
