default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2344 # Atualize se necessário
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: horsesinpocket_development

test:
  <<: *default
  database: horsesinpocket_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: horsesinpocket_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || '127.0.0.1' %>
  port: <%= ENV['DATABASE_PORT'] || 5432 %>
  sslmode: <%= ENV['DATABASE_SSLMODE'] || 'disable' %>
