default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: 2344 # Atualize se necessário
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: horsesinpocket_development

test:
  <<: *default
  database: horsesinpocket_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> # Use DATABASE_URL para simplificar a configuração
