default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: horsesinpocket_development
  username: postgres
  password: 2344
  host: 127.0.0.1
  port: 5432

test:
  <<: *default
  database: horsesinpocket_test
  username: postgres
  password: 2344
  host: 127.0.0.1
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  sslmode: require
